[package]
name = "day6"
version = "0.1.0"
authors = ["Joel Howard <joel.howard@protonmail.com>"]

[lib]
name = "day6"
path = "src/lib.rs"

[[bin]]
name = "day6-main"
path = "src/bin.rs"

[dependencies]
